// <auto-generated />
namespace _1263087.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddRelationalData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRelationalData));
        
        string IMigrationMetadata.Id
        {
            get { return "202111011650067_AddRelationalData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
